import './globals.css';
import '@/lib/highlight/light.css';
import type { Metadata } from 'next';
import { Providers } from './providers';
import PageContainer from '@/components/PageContainer';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning lang="zh-Hans">
      <body className="bg-slate-50 dark:bg-slate-950">
        <Providers>
          <PageContainer>
            <Header />
            <div className="container mx-auto">{children}</div>
          </PageContainer>
        </Providers>

        {/* TODO APP 查看案例写法 */}
        {process.env.NODE_ENV === 'production' && (
          <script
            dangerouslySetInnerHTML={{
              __html: `
                var _hmt = _hmt || [];
                (function() {
                  var hm = document.createElement("script");
                  hm.src = "https://hm.baidu.com/hm.js?f5f184c47aeb4306db0ff5ccce7c1e2b";
                  var s = document.getElementsByTagName("script")[0];
                  s.parentNode.insertBefore(hm, s);
                })();
            `,
            }}
          />
        )}
      </body>
    </html>
  );
}
